### ISSUE TITLE
Resize issue

### ISSUE THREAD

**Issue by wesleyotugo** [doctormo/GimpPs#3]
Not really a strong issue but after coping and starting gimp it seemed odd but using my mouse to resize it seem to solve the problem

**Comment by doctormo** [comment]
I don't understand. Do you have a screenshot?

**Comment by wesleyotugo** [comment]
the docks has resized automatically

**Comment by fscale** [comment]
For anyone who is having trouble with the GIMP window being twice their screen's size vertically after applying this theme, here's what I did to fix the issue on a 1366x768 display:

- Have GIMP open with the GimpPS theme applied.
- Resize the toolbox on the left by clicking and dragging the edge so that the toolbox becomes two columns wide.
- In your computer's display settings, set your display to be rotated either 90° CW or CCW.
- Resize the window vertically until the window refuses to get smaller.
- Change your display back.

**Comment by saisasidhar** [comment]
Doing the following before resizing window(as suggested by @fscale) fixes the issue with single column toolbar.

Uncomment line 42(the answer to 1366x768, GimpPS and everything) in file ` ~/.gimp-2.8/themes/PsIcons/gtkrc` 

`# GtkWidget::focus-padding         = 0`

This should enable creation of familiar two column layout of Photoshop for small resolution screens.
